### ISSUE TITLE
No sensor available

### ISSUE THREAD

**Issue by vajpeyianirudh** [larics/optoforce-ros-pusblisher#2]
Hi
I have OptoForce HEX-70-CE-2000N sensor with me and when I run the node i receive the message 'No sensor available'. Am I missing any dependency necessary for the package or in general on the USB ports. I am able to see device with command 'lsusb' on the terminal.

Hope you can help.

Thanks

**Comment by suiauthon** [comment]
Hi, which branch are you using? Try with onrobot

**Comment by vajpeyianirudh** [comment]
Yes, It is a part of On robot only. Do I need to install any other driver? Maybe it is not able to recognize the port with the command 
ports.getlastsize()>0
any suggestions on that?

Thanks in advance

**Comment by vajpeyianirudh** [comment]
been able to solve the issue
